apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskapi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/xmurungi/taskapi-devops   # your actual repo URL
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc          # the local cluster
    namespace: taskapi
  syncPolicy:
    automated:
      prune: true         # delete resources removed from Git
      selfHeal: true      # revert manual kubectl changes that drift from Git
    syncOptions:
      - CreateNamespace=true