apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: xmurungi/${{ values.name }}
spec:
  type: service
  lifecycle: experimental
  owner: platform-team